# Generated by Django 4.0 on 2025-10-23 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=200)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignment_attachments/')),
                ('description', models.TextField()),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Assigned', max_length=50)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itapp.developer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itapp.project')),
            ],
        ),
    ]
