# Generated by Django 4.0 on 2025-10-23 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0003_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_description', models.TextField()),
                ('update_date', models.DateField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignment_updates/')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itapp.assignment')),
            ],
        ),
    ]
