# Generated by Django 4.0 on 2025-11-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0004_assignmentupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='lname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamlead',
            name='lname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamlead',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
