# Generated by Django 4.0 on 2025-11-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0005_developer_lname_developer_username_teamlead_lname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team_lead',
        ),
    ]
