# Generated by Django 4.0 on 2025-11-04 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0006_remove_project_attachment_remove_project_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignTeamLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='project_attachments/')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itapp.project')),
                ('team_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itapp.teamlead')),
            ],
        ),
    ]
