# Generated by Django 4.0 on 2025-11-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0007_assignteamlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignteamlead',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
