# Generated by Django 4.0 on 2025-11-04 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0008_assignteamlead_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itapp.teamlead'),
        ),
    ]
