# Generated by Django 4.0 on 2025-11-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0009_assignment_team_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
