# Generated by Django 4.0 on 2025-11-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0011_assigntlupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigntlupdate',
            old_name='assigntl',
            new_name='assignment',
        ),
    ]
