# Generated by Django 4.2.15 on 2025-11-12 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0013_project_end_date_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itapp.teamlead'),
        ),
    ]
