# Generated by Django 4.2.15 on 2025-11-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0014_developer_team_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approve',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
