# Generated by Django 4.2.15 on 2025-11-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0015_customuser_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
