# Generated by Django 4.2.15 on 2025-11-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0016_assignment_end_date_assignment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignteamlead',
            name='clear',
            field=models.BooleanField(default=False),
        ),
    ]
