# Generated by Django 4.2.15 on 2025-11-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0017_assignteamlead_clear'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='clear',
            field=models.BooleanField(default=False),
        ),
    ]
