# Generated by Django 4.2.15 on 2026-03-20 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0018_assignment_clear'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itapp.developer')),
                ('teamlead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itapp.teamlead')),
            ],
        ),
    ]
