# Generated by Django 4.2.15 on 2026-03-20 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0019_devchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMeet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('meet_link', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itapp.teamlead')),
            ],
        ),
    ]
