# Generated by Django 4.2.15 on 2026-03-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0020_teammeet'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlead',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='teamlead_photos/'),
        ),
    ]
