# Generated by Django 4.2.15 on 2026-03-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itapp', '0021_teamlead_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='developer_photos/'),
        ),
    ]
